◁ Final attempt with oldrel-1
- Issues with current R version 4.4.0 since oldrel works with previous to most current version. Testing with 4.3.0.

Creating lockfile '.github/pkg.lock'

  ✔ Updated metadata database: 5.47 MB in 10 files.

  ℹ Creating lockfile '.github/pkg.lock'
  ℹ Updating metadata database
  ✔ Updating metadata database ... done

  ℹ Creating lockfile '.github/pkg.lock'
  ✖ Creating lockfile '.github/pkg.lock' [10.4s]

  Error:
  ! error in pak subprocess
  Caused by error:
  ! Could not solve package dependencies:
  * deps::.: Needs R >= 4.4.0
  * any::sessioninfo: dependency conflict
  * any::rcmdcheck: dependency conflict
  ---
  Backtrace:
  1. pak::lockfile_create(c(deps, extra_deps), lockfile = ".github/pkg.lock", …
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_create_internal", asNamespace("pak"))(...)
  3. prop$stop_for_solution_error()
  4. private$plan$stop_for_solve_error()
  5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
  6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
  7. | base::signalCondition(cond)
  8. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.